### ISSUE TITLE
Creating a pool with an already existing name doesn't return an error

### ISSUE THREAD

**Issue by valcharry** [josephgorse/ipam-client#1]
Created 'TEST' pool several times. No error was returned but pools created with empty string names were created.
<img width="366" alt="screen shot 2016-11-04 at 10 46 25 am" src="https://cloud.githubusercontent.com/assets/13005237/20009741/01e451bc-a27c-11e6-8008-dc89255910a4.png">

**Comment by josephgorse** [comment]
Fixed by [412958692eaabcd3adadf248006f7dd13c75c165](https://github.com/josephgorse/ipam-client/commit/412958692eaabcd3adadf248006f7dd13c75c165)
